spring:
  application:
    name: @project.name@
  data:
    rest:
      base-path: /v1

server:
  port: ${CLIENT_SERVER_PORT:8081}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
